#! /bin/sh

xrandr --output eDP-1 --mode 1366x768 --pos 1920x312 --rotate normal --output HDMI-1 --off --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-2 --off
sxhkd &
picom --config ~/.config/compton/compton.conf &
bash ~/.config/polybar/launch.sh &
nitrogen --restore &


bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X


bspc config border_width         2
bspc config window_gap           6 
bspc config top_padding          0
bspc config bottom_padding       0

bspc config focused_border_color      "#50fa7b"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a steam state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
