#! /bin/sh

sxhkd &
picom --config ~/.config/compton/compton.conf &
bash ~/.config/polybar/launch.sh &
nitrogen --restore &


bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X


bspc config border_width         0
bspc config window_gap          20 
bspc config top_padding         6
bspc config bottom_padding       0

bspc config focused_border_color	      "#ED6A69"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a steam state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
